/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperacoesRouteImport } from './routes/operacoes'
import { Route as CaminhoesIndexRouteImport } from './routes/caminhoes.index'
import { Route as CaminhoesFamilyRouteImport } from './routes/caminhoes.$family'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRoute = OperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaminhoesIndexRoute = CaminhoesIndexRouteImport.update({
  id: '/caminhoes/',
  path: '/caminhoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaminhoesFamilyRoute = CaminhoesFamilyRouteImport.update({
  id: '/caminhoes/$family',
  path: '/caminhoes/$family',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/operacoes': typeof OperacoesRoute
  '/caminhoes/$family': typeof CaminhoesFamilyRoute
  '/caminhoes/': typeof CaminhoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/operacoes': typeof OperacoesRoute
  '/caminhoes/$family': typeof CaminhoesFamilyRoute
  '/caminhoes': typeof CaminhoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/operacoes': typeof OperacoesRoute
  '/caminhoes/$family': typeof CaminhoesFamilyRoute
  '/caminhoes/': typeof CaminhoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/operacoes' | '/caminhoes/$family' | '/caminhoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/operacoes' | '/caminhoes/$family' | '/caminhoes'
  id: '__root__' | '/' | '/operacoes' | '/caminhoes/$family' | '/caminhoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OperacoesRoute: typeof OperacoesRoute
  CaminhoesFamilyRoute: typeof CaminhoesFamilyRoute
  CaminhoesIndexRoute: typeof CaminhoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes': {
      id: '/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof OperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caminhoes/': {
      id: '/caminhoes/'
      path: '/caminhoes'
      fullPath: '/caminhoes/'
      preLoaderRoute: typeof CaminhoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caminhoes/$family': {
      id: '/caminhoes/$family'
      path: '/caminhoes/$family'
      fullPath: '/caminhoes/$family'
      preLoaderRoute: typeof CaminhoesFamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OperacoesRoute: OperacoesRoute,
  CaminhoesFamilyRoute: CaminhoesFamilyRoute,
  CaminhoesIndexRoute: CaminhoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
