/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaminhoesIndexRouteImport } from './routes/caminhoes.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaminhoesIndexRoute = CaminhoesIndexRouteImport.update({
  id: '/caminhoes/',
  path: '/caminhoes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caminhoes/': typeof CaminhoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caminhoes': typeof CaminhoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caminhoes/': typeof CaminhoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caminhoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caminhoes'
  id: '__root__' | '/' | '/caminhoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaminhoesIndexRoute: typeof CaminhoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caminhoes/': {
      id: '/caminhoes/'
      path: '/caminhoes'
      fullPath: '/caminhoes/'
      preLoaderRoute: typeof CaminhoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaminhoesIndexRoute: CaminhoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
